[build]
  base = "admin"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  VITE_BACKEND_URL = "https://textuser-ecom.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  publish = "admin/dist"
  port = 5173


