[build]
  command = "cd admin && npm install && npm run build"
  publish = "admin/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  publish = "admin/dist"
  port = 5173


